import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    // './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    // './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'almost-black': '#171715',
        'sekundarna-tamna': '#11201D',
        'primarna-tamna': '#192E29',
        'accent-boja': '#8B9554',
        'primarna-svijetla': '#C3C6B6',
        'sekundarna-svijetla': '#DDDFD6',
        'almost-white': '#F8F7F2',
        'dark-mode-bg': '#11201D',
        'light-mode-bg': '#DDDFD6',
        'dark-mode-proziran-bg': '#11201D3D',
        'light-mode-proziran-bg': '#DDDFD68C',
        'heading-color-light-mode': '#192E29',
        'nadnaslov-color-light-mode': '#8B9554',
        'text-light-mode': '#11201D',
        'heading-color-dark-mode': '#C3C6B6',
        'nadnaslov-color-dark-mode': '#8B9554',
        'text-dark-mode': '#DDDFD6',
        'hero-heading-color-light-mode': '#192E29',
        'hero-nadnaslov-color-light-mode': '#8B9554',
        'hero-text-light-mode': '#11201D',
        'hero-heading-color-dark-mode': '#C3C6B6',
        'hero-nadnaslov-color-dark-mode': '#8B9554',
        'hero-text-dark-mode': '#DDDFD6',
        'kartice-autor-datum-light-mode': '#827D7D',
        'kartice-autor-datum-dark-mode': '#C1BABA',
        'dark-mode-obrub': '#8B9554',
        'light-mode-obrub': '#C3C6B6',
        'cta-znaka-dark-mode': '#8B9554',
        'cta-znaka-light-mode': '#8B9554',
        'kartice-divider-light-mode': '#C1BABA',
        'kartice-divider-dark-mode': '#3F3B3B',
        'overlay-dark': '#11201D75',
        'overlay-light': '#FFFFFF7A',
        'gray-dark': '#3F3B3B',
        'error-boja': '#FF7A00',
        'good-boja': '#C6FF00',
        'info-boja': '#8C946F',
        'gray-base': '#827D7D',
        'gray-light': '#C1BABA',
        black: '#000000',
        'brand-color-main': '#FF0000',
        'brand-color-secondary': '#F5D76F',
        white: '#FFFFFF',
      },

      //BG-COLORS-BUTTON
      backgroundImage: {
        sutraGradientButton: 'linear-gradient(180deg, rgba(90,93,82,1) 0%, rgba(36,41,40,1) 100%)',
        sutraGradientButtonDark: 'linear-gradient(180deg, rgba(188,192,175,1) 0%, rgba(178,182,137,1) 100%)',
        'gradient-light': 'linear-gradient(#fffbf6ff 0%, #dcc39dff 100%)',
        'gradient-dark': 'linear-gradient(#5a5d52ff 0%, #242928ff 100%)',
        'gradient-ferlauftamni': 'linear-gradient(#000000ff 0%, #00000000 100%)',
        'gradient-ferlaufbijeli': 'linear-gradient(#ffffffff 0%, #ffffffff 100%)',
        'gradient-light-radial': 'radial-gradient(circle, #fffbf6ff, #dcc39dff)', // Pretpostavljeni radijalni gradijent
        'gradient-dark-radial': 'radial-gradient(circle, #5a5d52ff, #242928ff)', // Pretpostavljeni radijalni gradijent
      },
      //OUTLINE
      outlineWidth: {
        sutraButtonOutline: '2px',
        sutraButtonOutlineAsPrim: '1px',
        sutraButtonOutlineAsPrimHover: '2.5px',
      },
      //OPACITY
      opacity: {
        ghostButtonOpacity: '0.5',
      },

      fontSize: {
        h1: '3.4375rem',
        h2: '2.5rem',
        h3: '1.875rem',
        h4: '1.3125rem',
        body: '1.125rem',
        default: '1rem',
        small: '0.875rem',
        tag: '0.75rem',
        contactFormSidebarHeading: '1.75rem',
        //////// FIGMA ///////
        h0_2xl: '4.5rem',
        h1_xl: '3.75rem',
        h2_lg: '3rem',
        h3_md: '2.25rem',
        h4_sm: '1,875rem',
        h5_xs: '1.5rem',
        xl: '1.25rem',
        lg: '1.125rem',
        md: '1rem',
        sm: '0.875rem',
        xs: '0.75rem',
        base: '1rem',

        /// MASTODONT UPDATE

        'h1-xl': ['3.5rem', { lineHeight: '70px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'h1-desktop': ['3rem', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1-tablet': ['2.25rem', { lineHeight: '43px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1-mobile35': ['1.75rem', { lineHeight: '35px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h2-xl': ['3rem', { lineHeight: '58px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'h2-desktop': ['2.5rem', { lineHeight: '50px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2-tablet': ['2.25rem', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2-mobile': ['2rem', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h3-xl': ['2.25rem', { lineHeight: '46px', fontWeight: '700' }],
        'h3-desktop': ['2rem', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h3-tablet': ['1.75rem', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h3-mobile': ['1.5rem', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h4-xl': ['1.875rem', { fontWeight: '700' }],
        'h4-desktop': ['1.625rem', { lineHeight: '34px', fontWeight: '700' }],
        'h4-tablet': ['1.375rem', { lineHeight: '28px', fontWeight: '700' }],
        'h4-mobile': ['1.25rem', { lineHeight: '26px', fontWeight: '700' }],
        'text-base-l-xl': ['1.25rem', { lineHeight: '28px', fontWeight: '400' }],
        'text-base-l-desktop': ['1.25rem', { lineHeight: '28px', fontWeight: '400' }],
        'text-base-l-mobiletablet': ['1.125rem', { lineHeight: '26px', fontWeight: '400' }],
        'text-base-base-xl': ['1.0625rem', { fontWeight: '400' }],
        'text-base-base-desktop': ['1rem', { lineHeight: '24px', fontWeight: '400' }],
        'text-base-base-mobiletablet': ['1rem', { fontWeight: '400' }],
        'text-base-small-xl': ['0.875rem', { lineHeight: '20px', fontWeight: '400' }],
        'text-base-small-desktop': ['0.75rem', { lineHeight: '18px', fontWeight: '400' }],
        'text-base-small-mobiletablet': ['0.625rem', { fontWeight: '400' }],
        'nadnaslov-xl': ['1.125rem', { fontWeight: '300' }],
        'nadnaslov-desktop': ['1rem', { lineHeight: '24px', fontWeight: '300' }],
        'nadnaslov-tablet': ['0.875rem', { lineHeight: '20px', fontWeight: '300' }],
        'nadnaslov-mobile': ['0.75rem', { lineHeight: '18px', fontWeight: '300' }],
        'button-xl': ['1.375rem', { letterSpacing: '0.01em', fontWeight: '400' }],
        'button-l': ['1.25rem', { letterSpacing: '0.02em', fontWeight: '400' }],
        'button-base': ['1rem', { letterSpacing: '0.02em', fontWeight: '400' }],
        'button-small': ['0.875rem', { letterSpacing: '0.03em', fontWeight: '400' }],
        'button-xs': ['0.875rem', { letterSpacing: '0.04em', fontWeight: '400' }],
        'quote-xl': ['1.375rem', { fontWeight: '700' }],
        'quote-desktop': ['1.25rem', { lineHeight: '30px', fontWeight: '700' }],
        'quote-tablet': ['1.125rem', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'quote-mobile': ['1rem', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'captions-xl': ['1rem', { fontWeight: '300' }],
        'captions-desktop': ['1rem', { lineHeight: '24px', fontWeight: '300' }],
        'captions-tablet': ['0.875rem', { lineHeight: '20px', fontWeight: '300' }],
        'captions-mobile': ['0.75rem', { lineHeight: '18px', fontWeight: '300' }],
        'all-caps-xl': ['1.25rem', { fontWeight: '400' }],
        'all-caps-large': ['1.25rem', { lineHeight: '30px', fontWeight: '400' }],
        'all-caps-medium': ['0.875rem', { letterSpacing: '0.01em', fontWeight: '600' }],
        'all-caps-small': ['0.625rem', { letterSpacing: '0.03em', fontWeight: '400' }],
        'menu-tabs-xl': ['1.125rem', { fontWeight: '400' }],
        'menu-tabs-desktop': ['1.125rem', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'menu-tabs-tablet': ['1rem', { letterSpacing: '0.02em', fontWeight: '400' }],
        'menu-tabs-mobile': ['1rem', { letterSpacing: '0.03em', fontWeight: '400' }],
        'tag-xl': ['1rem', { fontWeight: '400' }],
        'tag-desktop': ['0.875rem', { fontWeight: '400' }],
        'tag-tablet': ['0.75rem', { fontWeight: '400' }],
        'tag-mobile': ['0.625rem', { fontWeight: '400' }],
        'brojcanik-xl': ['1.875rem', { fontWeight: '900' }],
        'brojcanik-desktop': ['1.5rem', { fontWeight: '900' }],
        'brojcanik-tablet': ['1.25rem', { fontWeight: '900' }],
        'brojcanik-mobile': ['1.125rem', { fontWeight: '900' }],
      },

      spacing: {
        'element-inside-btn-l': '10px',
        'element-inside-btn-m': '7px',
        'element-inside-btn-s': '5px',
        'tag-element-inside-xl': '10px',
        'tag-element-inside-desktop': '8px',
        'tag-element-inside-tablet': '6px',
        'tag-element-inside-mobile': '5px',
      },

      padding: {
        'botun-xl-td': '10px',
        'botun-xl-lr': '15px',
        'botun-l-td': '8px',
        'botun-l-lr': '11px',
        'botun-base-td': '8px',
        'botun-base-lr': '10px',
        'botun-s-td': '6px',
        'botun-s-lr': '10px',
        'botun-xs-td': '6px',
        'botun-xs-lr': '10px',
        'tag-xl-td': '8px',
        'tag-xl-lr': '11px',
        'tag-desktop-td': '8px',
        'tag-desktop-lr': '10px',
        'tag-tablet-td': '7px',
        'tag-tablet-lr': '10px',
        'tag-mobile-td': '3px',
        'tag-mobile-lr': '6px',
      },

      borderRadius: {
        'botun-xl': '1px',
        'botun-l': '1px',
        'botun-base': '7px',
        'botun-s': '6px',
        'botun-xs': '8px',
        'single-icon-xl': '22px',
        'single-icon-l': '22px',
        'single-icon-base': '22px',
        'single-icon-s': '22px',
        'single-icon-xs': '22px',
        'tag-xl': '33px',
        'tag-desktop': '22px',
        'tag-tablet': '17px',
        'tag-mobile': '55px',
      },

      lineHeight: {
        sutraCardTitleLineHeight: '32px',
      },
      maxWidth: {
        sutraBlogTestMaxWidth: '750px',
        sutraContactUsTempFormWidth: '1200px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('tailwind-scrollbar'), require('@tailwindcss/forms')],
};
export default config;
