export const cookiesUsed = [
  {
    name: 'CLID',
    value: '1042020a61be4da29ed32918ce74abde.20240902.20250909',
    domain: 'www.clarity.ms',
    path: '/',
    expiry: '2025-09-09T07:49:13.541Z',
    size: 54,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr:
      'Koristi Microsoft Clarity za identificiranje pojedinih korisnika preko različitih domena u svrhu analitike.',
    descriptionEng:
      'Used by Microsoft Clarity to identify individual users across different domains for analytics purposes.',
    descriptionIta:
      'Utilizzato da Microsoft Clarity per identificare utenti individuali su diversi domini per scopi analitici.',
    descriptionGer:
      'Verwendet von Microsoft Clarity zur Identifizierung einzelner Benutzer über verschiedene Domains für Analysezwecke.',
  },
  {
    name: 'MUID',
    value: '0ED3E42060AA6EAE1969F0CE61EE6F8A',
    domain: '.clarity.ms',
    path: '/',
    expiry: '2025-09-27T09:03:23.734Z',
    size: 36,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'High',
    descriptionHr:
      'Microsoft kolačić koji identificira jedinstvene korisnike za praćenje njihovih interakcija s web-mjestom.',
    descriptionEng:
      'Microsoft cookie used for identifying unique web users for tracking their interaction with the website.',
    descriptionIta:
      'Cookie Microsoft utilizzato per identificare utenti web unici e tracciare le loro interazioni con il sito.',
    descriptionGer:
      'Microsoft-Cookie zur Identifizierung einzigartiger Webbenutzer zur Verfolgung ihrer Interaktionen mit der Website.',
  },
  {
    name: 'PH_HPXY_CHECK',
    value: 's1',
    domain: 'cms.sutra.hr',
    path: '/',
    expiry: 'Session',
    size: 15,
    httpOnly: false,
    secure: false,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Kolačić sesije koji server koristi za otkrivanje i sprječavanje mogućih napada CSRF.',
    descriptionEng:
      'Session cookie used by the server to detect and prevent potential cross-site request forgery (CSRF).',
    descriptionIta: 'Cookie di sessione utilizzato dal server per rilevare e prevenire potenziali attacchi CSRF.',
    descriptionGer:
      'Session-Cookie, das vom Server verwendet wird, um potenzielle CSRF-Angriffe zu erkennen und zu verhindern.',
  },
  {
    name: '__insp_nv',
    value: 'false',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:16:29.265Z',
    size: 14,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr:
      'Kolačić za analitiku Inspectlet koji se koristi za reprodukciju sesija i praćenje korisničke navigacije.',
    descriptionEng:
      'Inspectlet analytics cookie used for session replays, tracking user navigation through the website.',
    descriptionIta:
      'Cookie di analisi Inspectlet utilizzato per riprodurre le sessioni e tracciare la navigazione degli utenti nel sito.',
    descriptionGer:
      'Inspectlet-Analyse-Cookie, das für Sitzungswiedergaben verwendet wird, um die Benutzernavigation durch die Website zu verfolgen.',
  },
  {
    name: '__insp_pad',
    value: '1',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:16:29.595Z',
    size: 11,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Inspectlet kolačić za bilježenje i praćenje korisničkih interakcija na web stranici.',
    descriptionEng: 'Inspectlet cookie used for capturing and recording user interactions on the website.',
    descriptionIta: 'Cookie Inspectlet utilizzato per catturare e registrare le interazioni degli utenti sul sito web.',
    descriptionGer: 'Inspectlet-Cookie zur Erfassung und Aufzeichnung von Benutzerinteraktionen auf der Website.',
  },
  {
    name: '__insp_sid',
    value: '2646540514',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:16:29.595Z',
    size: 20,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Kolačić za pohranu jedinstvenog ID-a sesije za Inspectlet snimanje sesija.',
    descriptionEng: 'Cookie for storing a unique session ID for Inspectlet session recordings.',
    descriptionIta:
      'Cookie utilizzato per memorizzare un ID di sessione univoco per le registrazioni di sessioni Inspectlet.',
    descriptionGer: 'Cookie zur Speicherung einer eindeutigen Sitzungs-ID für Inspectlet-Sitzungsaufzeichnungen.',
  },
  {
    name: '__insp_slim',
    value: '1725886637610',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:57:17.610Z',
    size: 24,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Kolačić koji koristi Inspectlet za praćenje performansi stranice i korisničkih interakcija.',
    descriptionEng: 'Cookie used by Inspectlet to monitor page performance and user interactions.',
    descriptionIta:
      'Cookie utilizzato da Inspectlet per monitorare le prestazioni della pagina e le interazioni degli utenti.',
    descriptionGer:
      'Cookie, der von Inspectlet verwendet wird, um die Seitenleistung und Benutzerinteraktionen zu überwachen.',
  },
  {
    name: '__insp_targlpt',
    value: 'U3V0cmEgbWFzdG9kb250',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:16:29.266Z',
    size: 34,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Koristi Inspectlet za praćenje ciljanih elemenata na stranici za analizu korisničkog ponašanja.',
    descriptionEng: 'Used by Inspectlet for tracking target elements on the page for user behavior analysis.',
    descriptionIta:
      'Utilizzato da Inspectlet per tracciare elementi target nella pagina per analizzare il comportamento degli utenti.',
    descriptionGer:
      'Verwendet von Inspectlet zur Verfolgung von Zielelementen auf der Seite zur Analyse des Benutzerverhaltens.',
  },
  {
    name: '__insp_targlpu',
    value: 'aHR0cHM6Ly9zdXRyYS1tYXN0b2RvbnQudmVyY2VsLmFwcC9ocg%3D%3D',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:16:29.265Z',
    size: 70,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr:
      'Pohranjuje kodirane URL-ove koje koristi Inspectlet za analizu interakcija korisnika s određenim elementima.',
    descriptionEng:
      'Stores encoded URL targets used by Inspectlet for analyzing user interactions with specific elements.',
    descriptionIta:
      'Memorizza URL codificati utilizzati da Inspectlet per analizzare le interazioni degli utenti con elementi specifici.',
    descriptionGer:
      'Speichert codierte URL-Ziele, die von Inspectlet zur Analyse von Benutzerinteraktionen mit bestimmten Elementen verwendet werden.',
  },
  {
    name: '__insp_uid',
    value: '731074419',
    domain: 'sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T12:16:29.595Z',
    size: 19,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr:
      'Jedinstveni ID korisnika koji postavlja Inspectlet za razlikovanje korisnika koji posjećuju web stranicu.',
    descriptionEng: 'A unique user ID cookie set by Inspectlet to distinguish different users visiting the website.',
    descriptionIta:
      'Cookie con ID utente univoco impostato da Inspectlet per distinguere gli utenti che visitano il sito.',
    descriptionGer:
      'Ein eindeutiger Benutzer-ID-Cookie, der von Inspectlet gesetzt wird, um verschiedene Benutzer zu unterscheiden, die die Website besuchen.',
  },
  {
    name: '_hjSessionUser_2686327',
    value: 'hj.2909.1097857',
    domain: '.sutra-mastodont.vercel.app',
    path: '/',
    expiry: '2025-09-09T13:01:18.000Z',
    size: 166,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Hotjar kolačić sesije koristi se za praćenje ponašanja korisnika tijekom sesije.',
    descriptionEng: 'Hotjar session cookie used to track user behavior during a session.',
    descriptionIta:
      'Cookie di sessione Hotjar utilizzato per tracciare il comportamento degli utenti durante una sessione.',
    descriptionGer:
      'Hotjar-Sitzungs-Cookie, das verwendet wird, um das Benutzerverhalten während einer Sitzung zu verfolgen.',
  },
  {
    name: 'asenha_tab',
    value: 'custom-code',
    domain: 'cms.sutra.hr',
    path: '/',
    expiry: '2025-09-10T10:01:37.000Z',
    size: 21,
    httpOnly: false,
    secure: false,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Kolačić koji koristi CMS za praćenje odabira kartica ili prilagođenih postavki koda.',
    descriptionEng: 'Cookie used by the CMS for tracking tab selections or custom-code settings.',
    descriptionIta:
      'Cookie utilizzato dal CMS per tracciare le selezioni delle schede o le impostazioni del codice personalizzato.',
    descriptionGer:
      'Cookie, der vom CMS verwendet wird, um Tab-Auswahlen oder benutzerdefinierte Code-Einstellungen zu verfolgen.',
  },
  {
    name: 'referral_code',
    value: 'null',
    domain: '.plerdy.com',
    path: '/',
    expiry: '2025-10-02T09:07:25.000Z',
    size: 17,
    httpOnly: false,
    secure: false,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'Plerdy kolačić za praćenje preporuka, koristi se za pohranu kodova preporuka za nove korisnike.',
    descriptionEng: 'Referral tracking cookie used by Plerdy to store referral codes for user acquisitions.',
    descriptionIta:
      'Cookie di tracciamento referral utilizzato da Plerdy per memorizzare i codici di riferimento per le acquisizioni di utenti.',
    descriptionGer:
      'Empfehlungsverfolgungs-Cookie, das von Plerdy verwendet wird, um Empfehlungscodes für Benutzerakquisitionen zu speichern.',
  },
  {
    name: 'wordpress_logged_in_367b94ee48563d009aacedc040478309',
    value:
      'mastodont%7C1726471436%7Cotfv3oFdVJNnACxtEL0l1QSWg5Q0xC9QwzAowZFXm2f%7C0c0abfc933dc794b7ea223347bd78a6e2d8eaa3897384502194ee89c8a751852',
    domain: 'cms.sutra.hr',
    path: '/',
    expiry: '2025-09-16T19:23:56.027Z',
    size: 187,
    httpOnly: true,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'WordPress kolačić koji održava korisnike prijavljenima u CMS tijekom sesije.',
    descriptionEng: 'WordPress cookie used to keep users logged into the CMS during their session.',
    descriptionIta: 'Cookie di WordPress utilizzato per mantenere gli utenti connessi al CMS durante la sessione.',
    descriptionGer:
      'WordPress-Cookie, der verwendet wird, um Benutzer während ihrer Sitzung im CMS angemeldet zu halten.',
  },
  {
    name: 'wordpress_test_cookie',
    value: 'WP%20Cookie%20check',
    domain: 'cms.sutra.hr',
    path: '/',
    expiry: 'Session',
    size: 40,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr: 'WordPress test kolačić za provjeru jesu li kolačići omogućeni u pregledniku.',
    descriptionEng: 'WordPress test cookie to check if cookies are enabled on the browser.',
    descriptionIta: 'Cookie di test di WordPress per verificare se i cookie sono abilitati nel browser.',
    descriptionGer: 'WordPress-Test-Cookie, um zu überprüfen, ob Cookies im Browser aktiviert sind.',
  },
  {
    name: 'wp-settings-1',
    value: 'libraryContent%3Dbrowse%26imgsize%3Dfull%26align%3Dleft%26editor%3Dtinymce',
    domain: 'cms.sutra.hr',
    path: '/',
    expiry: '2025-09-04T19:04:47.180Z',
    size: 87,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr:
      'Kolačić koji WordPress koristi za prilagođavanje korisničkog sučelja CMS-a prema korisničkim preferencijama.',
    descriptionEng: 'Cookie used by WordPress to customize the user interface of the CMS based on user preferences.',
    descriptionIta:
      'Cookie utilizzato da WordPress per personalizzare l&apos;interfaccia utente del CMS in base alle preferenze dell&apos;utente.',
    descriptionGer:
      'Cookie, das von WordPress verwendet wird, um die Benutzeroberfläche des CMS basierend auf den Benutzereinstellungen anzupassen.',
  },
  {
    name: 'wp-settings-time-1',
    value: '1725476686',
    domain: 'cms.sutra.hr',
    path: '/',
    expiry: '2025-09-04T19:04:47.181Z',
    size: 28,
    httpOnly: false,
    secure: true,
    sameSite: 'None',
    priority: 'Medium',
    descriptionHr:
      'Kolačić koji pohranjuje vremensku oznaku posljednje prilagodbe korisničkog sučelja u WordPress CMS-u.',
    descriptionEng: 'Cookie storing the timestamp of the last customization made by the user in the WordPress CMS.',
    descriptionIta:
      'Cookie che memorizza il timestamp dell&apos;ultima personalizzazione apportata dall&apos;utente nel CMS di WordPress.',
    descriptionGer:
      'Cookie, das den Zeitstempel der letzten vom Benutzer vorgenommenen Anpassung im WordPress-CMS speichert.',
  },
];
