name: Deploy if Blog Changed

on:
  schedule:
    - cron: '0 7,11,15 * * *' # 3 puta dnevno
  workflow_dispatch:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (for storing hash)
        uses: actions/checkout@v3

      - name: Fetch latest 20 blog modified dates from CMS
        run: |
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CMS_AUTH_TOKEN }}" \
            --data '{
              "query": """
                query {
                  allBlog(first: 20, where: {orderby: {field: MODIFIED, order: DESC}}) {
                    nodes {
                      databaseId
                      modifiedGmt
                    }
                  }
                }
              """
            }' \
            ${{ secrets.CMS_GRAPHQL_ENDPOINT }} \
          | jq -r '.data.allBlog.nodes[] | "\(.databaseId):\(.modifiedGmt)"' \
          | paste -sd ";" - > blog_versions.txt

      - name: Generate SHA256 hash
        run: |
          cat blog_versions.txt
          sha256sum blog_versions.txt | cut -d ' ' -f1 > current_hash.txt

      - name: Load previous hash (if exists)
        id: load_previous
        run: |
          if [ -f .last_blog_hash ]; then
            cat .last_blog_hash
          else
            echo "No previous hash"
          fi

      - name: Compare hashes and deploy if changed
        run: |
          PREVIOUS=$(cat .last_blog_hash 2>/dev/null || echo "none")
          CURRENT=$(cat current_hash.txt)

          echo "Previous: $PREVIOUS"
          echo "Current:  $CURRENT"

          if [ "$PREVIOUS" != "$CURRENT" ]; then
            echo "Blog content changed. Triggering deploy..."
            curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
            echo "$CURRENT" > .last_blog_hash
          else
            echo "No changes detected. Skipping deploy."
          fi

      - name: Commit updated hash
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update blog hash
          file_pattern: .last_blog_hash
