name: Scheduled Vercel Deploy

on:
  schedule:
    - cron: '0 7,11,15 * * *' # 09:00, 13:00, 17:00
  workflow_dispatch: # Opcionalno: ručno pokretanje iz GitHub sučelja

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment via Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
